name: monolog
description: Simple extensible logging framework.
version: 1.0.0
homepage: https://github.com/jacovdbosch/monolog
authors:
  - Jaco van den Bosch <jacovdboschjr@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
